#!/usr/bin/env bash
#
if [ -e "school" ]
then
echo "school file exists"

if [ -s "school" ]
then
echo "school file is not empty"
	                
elif [ -f "school" ]
then
echo "school is a regular file"
else
echo "school file is empty"
fi
else
echo "school file does not exist"
fi
