#!/usr/bin/env bash
#
f="school"
if [ -e $f ]
then
	echo "school file exist"
	if [ -s $f ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f $f]
	then
		echo "school file is a regular file"
	fi
else
	echo "school file does not exist"
fi
