#!/usr/bin/env bash
#
if [ -e "school" ]
then
	echo "school file exists"
fi
if [ -f "school" ]
then
	echo "school file is a regular file"
fi
if [ -s "school" ]
then
	echo "school file is not empty"
else
	echo "school file does not exist"
fi
